version: 2
updates:
- package-ecosystem: pip
  directory: "/src"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Madrid
  open-pull-requests-limit: 10
  commit-message:
    prefix: "[Dep][pip] "
  labels:
    - dependabot

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Madrid
  open-pull-requests-limit: 10
  commit-message:
    prefix: "[Dep][docker] "
  labels:
    - dependabot
